version: '3.8'
services:
  app:
    build: .
    ports:
      - "8081:8080"
    depends_on:
      liquibase:
        condition: service_completed_successfully
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=BinaryTree
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    stdin_open: true
    tty: true

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=BinaryTree
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  liquibase:
    image: liquibase/liquibase:4.27.0
    command: --url="jdbc:postgresql://db:5432/BinaryTree?user=postgres&password=postgres" --changeLogFile=/changelog/db-changelog.yaml update
    volumes:
      - ./db/changelog/schema1/table/changelog.yaml:/changelog/db-changelog.yaml
    depends_on:
      db:
        condition: service_healthy