version: '3.8'
services:
  app:
    build: .
    ports:
      - "8081:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=BinaryTree
      - DB_UER=postgres
      - DB_PASSWORD=postgres
    stdin_open: true
    tty: true
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=BinaryTree
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"