# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: binary-tree-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: binary-tree
  template:
    metadata:
      labels:
        app: binary-tree
    spec:
      containers:
        - name: binary-tree
          image: ECR_REPOSITORY_URL:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: binary-tree-service
  namespace: default
spec:
  selector:
    app: binary-tree
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer